apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd2
  name: httpd2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd2
    spec:
      hostname: httpd2
      subdomain: httpd2-subdomain 
      containers:
      - image: registry.redhat.io/rhscl/httpd-24-rhel7
        name: httpd-24-rhel7

