apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd1
  name: httpd1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd1
    spec:
      hostname: httpd1
      subdomain: httpd1-subdomain 
      containers:
      - image: registry.redhat.io/rhscl/httpd-24-rhel7
        name: httpd-24-rhel7

