apiVersion: v1
kind: Service
metadata:
  name: httpd1-subdomain 
  namespace: httpd-svc-demo
spec:
  selector:
    app: httpd1
  clusterIP: None
  ports:
  - name: foo # name is not required for single-port Services
    port: 8080
    targetPort: 8080
